export const CART_ADD_ITEM = "CART_ADD_ITEM";
export const CART_REMOVE_ITEM = "CART_REMOVE_ITEM";
export const CART_CLEAR_ITEM_REQUEST = "CART_CLEAR_ITEM_REQUEST";
export const CART_CLEAR_ITEM_SUCCESS = "CART_CLEAR_ITEM_SUCCESS";
export const CART_SET_ITEM_QTY = "CART_SET_ITEM_QTY";
